version: '3'

services:
  lsys-logstash:
    build: server/logstash
    hostname: lsys-logstash
    user: "${CONTAINER_USER}:${CONTAINER_GROUP}"
    ports:
      - 5044:5044

  lsys-elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch-wolfi:9.1.5
    hostname: lsys-elastic
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD="minipot13ar59aBz"
    mem_limit: 1g

  lsys-kibana:
    image: docker.elastic.co/kibana/kibana:9.1.5
    hostname: lsys-kibana
    ports:
      - 5601:5601
      
  # lsys-elastic:
  #   build: server/elastic
  #   hostname: lsys-elastic
  #   ports:
  #     - 9200:9200
