version: '3'

services:
  lsys-logstash:
    build: server/logstash
    hostname: lsys-logstash
    user: "${CONTAINER_USER}:${CONTAINER_GROUP}"
    environment:
      - LOGSTASH_STDOUT=true
      - LOGSTASH_DISABLE_DIET=false
    ports:
      - 5044:5044

  lsys-elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch-wolfi:9.1.5
    hostname: lsys-elastic
    ports:
      - 127.0.0.1:9200:9200
      - 127.0.0.1:9300:9300
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    mem_limit: 1g
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data

  lsys-kibana:
    image: docker.elastic.co/kibana/kibana:9.1.5
    hostname: lsys-kibana
    environment:
      - xpack.security.enabled=false
      - ELASTICSEARCH_HOSTS=http://lsys-elastic:9200
    depends_on:
      - lsys-elastic
    ports:
      - 127.0.0.1:5601:5601
      
  lsys-kibana-initialize:
    image: curlimages/curl:8.16.0
    container_name: lsys-kibana-initialize
    depends_on:
      - lsys-kibana
    volumes:
      - ./server/kibana-init/init.sh:/init.sh:ro
      - ./server/kibana-init/init.ndjson:/data/init.ndjson:ro
    command: /bin/sh /init.sh
